spring:
  application:
    name: audition-api
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    problemdetails:
      enabled: true
    throw-exception-if-no-handler-found: true
  sleuth:
    sampler:
      probability: 1.0
server:
  max-http-request-header-size: 16KB
  port: 8080
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info, health
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

audition:
  api:
    version: 1
    connectTimeoutInSecs: 30
    readTimeoutInSecs: 60
  integration:
    client:
      api:
        host: "https://jsonplaceholder.typicode.com"
        auditionPostsPath: "/posts"
        auditionPostPath: "/posts/{postId}"
        auditionPostCommentsPath: "/posts/{postId}/comments"
        auditionCommentsPath: "/comments"