server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  mvc:
    problemdetails:
      enabled: true

management:
  metrics:
    enable:
      all: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus